apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: postgres
  namespace:  drawzy-staging
  labels:
    app:  postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  postgres
  template:
    metadata:
      labels:
        app:  postgres
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image:  postgres:17.7
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap 
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap 
                  key:  POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret 
                  key:  POSTGRES_PASSWORD